Pinecone updater
StampyAI/alignment-research-dataset pull request #115
Opened 2023-08-04 17:58 UTC by henri123lemoine

Modified the articles table model, added pinecone_update_required, pinecone_delete_required, and incomplete, based on whether an article needs to be updated, deleted and refetched, respectively. Fixed the pinecone updating, such that now running `python3 main.py pinecone_update [sources]` successfully updates the Pinecone vector db with the articles that need to be updated.
TODO: fix inefficiencies in pinecone updating, fix bugs related to fetching some sources

2023-08-06 13:01 UTC, mruwnik requested changes

2023-08-06 13:01 UTC, mruwnik commented on align_data/db/models.py
> +            key != 'entry_id' and getattr(self, key, None) != getattr(other, key, None)
[NIT] this can fail if e.g 'bla' gets added to `PINECONE_METADATA_KEYS`, which should probably cause an error or something, rather than silently accept missing keys. This is a long way of saying that you don't need to check whether `key != 'entry_id'` for this to work, as `getattr(self, 'entry_id', None) == None`. So you can just do a basic `return all(getattr(self, key, None) == getattr(other, key, None)  for key in PINECONE_METADATA_KEYS)` if you don't care about nonexistent properties

2023-08-06 13:01 UTC, mruwnik commented on align_data/pinecone/update_pinecone.py
> +        if value == "":
you might want to do a `if value.strip() == ''` or even `if not value.strip()`

2023-08-06 13:31 UTC, henri123lemoine commented on align_data/pinecone/update_pinecone.py
> +                session.merge(article)
I used to have session.add(article), but started getting an `sqlalchemy.exc.InvalidRequestError: Object '<Article at 0x7f2eabb7b790>' is already attached to session '2' (this is '1')` error. Switching back to merge temporarily fixed the issue, but I agree that merge is unnecessary. And I just realized this was occurring because of stream_pinecone_updates. so I'll fix asap.

2023-08-06 13:40 UTC, henri123lemoine commented on align_data/db/models.py
> +            raise ValueError(f"Entry is missing the following field(s): {','.join([missing for missing in self.__id_fields if not getattr(self, missing)])}")
Ok, another way is to calculate the hash_id directly in the add_entries method, then. I'll do that.

2023-08-06 13:42 UTC, mruwnik commented on align_data/db/models.py
> +            raise ValueError(f"Entry is missing the following field(s): {','.join([missing for missing in self.__id_fields if not getattr(self, missing)])}")
why there? It's currently done in `before_write`

2023-08-06 13:47 UTC, henri123lemoine commented on align_data/db/models.py
> +            key != 'entry_id' and getattr(self, key, None) != getattr(other, key, None)
Yeah I used to have it that way, and I guess it's more concise and the extra thing is unnecessary, but I thought it was more readable in case people wanted to understand/change/etc it in the future. It needs to be clear that entry_id is not relevant to this comparison method. Maybe a simple comment+code change to your version would be better?

2023-08-06 13:53 UTC, henri123lemoine commented on align_data/db/models.py
> +            raise ValueError(f"Entry is missing the following field(s): {','.join([missing for missing in self.__id_fields if not getattr(self, missing)])}")
Because as it currently is, the add_entries method needs the hash_id of an Article to know if it needs to be inserted or updated. But am I understanding correctly now that I can assume that the only entries add_entries will receive are those that need updating? If so, that won't be necessary anymore ofc.

2023-08-06 14:09 UTC, mruwnik commented on align_data/db/models.py
> +            raise ValueError(f"Entry is missing the following field(s): {','.join([missing for missing in self.__id_fields if not getattr(self, missing)])}")
adding, to be precise. Or if they need updating, then it's up to the caller. But yes

2023-08-06 14:10 UTC, mruwnik commented on align_data/db/models.py
> +            key != 'entry_id' and getattr(self, key, None) != getattr(other, key, None)
totally up to you :D When I prefix something with `[NIT]` I'm mainly just adding small suggestions, which you're totally free to completely ignore

2023-08-06 14:35 UTC, henri123lemoine commented on align_data/common/alignment_dataset.py
> +                    upsert(session, entry, existing_articles_map)
Ah, I see. But that's not yet in my branch, right? Which leads to there being a bunch of duplicate errors if I just use add or add_all in add_entries, as per my tests. In which case, I'm not sure what I should do at this point regarding add_entries. And please tell me if I'm totally off base regarding ^.

2023-08-06 14:38 UTC, mruwnik commented on align_data/common/alignment_dataset.py
> +                    upsert(session, entry, existing_articles_map)
what do your tests look like? In general try to avoid changing the code to make tests easier - the tests shouldn't influence the code in any way (other than showing where things are failing)

2023-08-06 14:40 UTC, mruwnik commented on align_data/common/alignment_dataset.py
> +                    upsert(session, entry, existing_articles_map)
If you're writing integration tests (i.e. with a real MySQL instance), you'll want to:
* setup a test database, so you're not using your local instance
* clean the database before each test (or at least certain batches of tests)
* delete the test database after you're finished

This can be tricky. Very tricky, even. I'd recommend just doing unit tests for now, and mocking out pinecone and mysql. And of course, as always, add an issue to do proper integration tests :D

2023-08-07 19:07 UTC, mruwnik approved these changes

2023-08-07 19:07 UTC, mruwnik commented on align_data/db/models.py
> +            raise NotImplemented
`raise NotImplementedError`

2023-08-07 19:14 UTC, henri123lemoine commented on align_data/db/models.py
> +            raise NotImplemented
Oh, right.

2023-08-07 19:51 UTC, henri123lemoine commented on align_data/db/models.py
> +            raise NotImplemented
NotImplementedError didn't really make sense in this case, nor did NotImplemented, so I replaced it by `raise TypeError(f"Expected an instance of Article, got {type(other).__name__}")`. Anyway, this method is not even used anymore so it could be deleted outright.

2023-08-07 20:35 UTC, Thomas-Lemoine submitted a review, later dismissed

2023-08-08 06:18 UTC, merged