Airtable: Take base and table IDs from environment
StampyAI/alignment-research-dataset pull request #200
Opened 2024-04-21 21:29 UTC by jbeshir

This avoids an issue where Airtable doesn't allow you to create API keys with access to bases you don't own, meaning only the owner of the airtable base added to the dataset can scrape it.

2024-04-22 06:08 UTC, mruwnik requested changes

2024-04-22 06:08 UTC, mruwnik commented on .env.example
> +AIRTABLE_BASE_ID=""
could you change this to `AGISF_AIRTABLE_BASE_ID` etc.? I'm a bit worried about what would happen if more airtable sources are added

2024-04-23 21:39 UTC, jbeshir commented on .env.example
> +AIRTABLE_BASE_ID=""
Changed, and also moved where they're used up a level so they're used when configuring the dataset, where the hardcoded IDs used to be, so the dataset-specific stuff stays separate from the general airtable stuff.

2024-04-24 08:06 UTC, mruwnik commented on .env.example
> +AIRTABLE_BASE_ID=""
nice! I was just about to ask you to do that :D

2024-04-24 08:07 UTC, mruwnik approved these changes

2024-04-24 08:07 UTC, merged