Add Dockerfile to run the scraper in a container
StampyAI/alignment-research-dataset pull request #201
Opened 2024-04-21 21:47 UTC by jbeshir

Adds a Dockerfile and makes a couple of small changes to make running in a serverless container environment easier:

- Takes a full DB connection URI rather than pieces of one, so it can use a UNIX domain socket to connect to the DB in environments which provide one of those. As implemented here, this requires updating the secrets feeding GitHub workflows to provide this instead of the individual pieces.
- Moves GCP credentials to a subdirectory rather than the root of the repository, so they can be mounted into the container as a volume from a secret.

2024-04-22 06:19 UTC, mruwnik requested changes

2024-04-22 06:19 UTC, mruwnik commented on align_data/settings.py
> +DB_CONNECTION_URI = os.environ.get("ARD_DB_CONNECTION_URI", "mysql+mysqlconnector://user:we all live in a yellow submarine@127.0.0.1:3306/alignment_research_dataset")
why not have support for both? i.e. something like:
```
if not (DB_CONNECTION_URI := os.environ.get("ARD_DB_CONNECTION_URI"):
    user = os.environ.get("ARD_DB_USER", "user")
    password = os.environ.get("ARD_DB_PASSWORD", "we all live in a yellow submarine")
    host = os.environ.get("ARD_DB_HOST", "127.0.0.1")
    port = os.environ.get("ARD_DB_PORT", "3306")
    db_name = os.environ.get("ARD_DB_NAME", "alignment_research_dataset")
    DB_CONNECTION_URI = f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{db_name}"
```
I'd like to keep the possibility of overriding single parameters, as it makes it easier to do quick changes

2024-04-22 06:19 UTC, mruwnik commented on .gitignore
> -credentials.json
keep em both

2024-04-23 21:36 UTC, jbeshir commented on align_data/settings.py
> +DB_CONNECTION_URI = os.environ.get("ARD_DB_CONNECTION_URI", "mysql+mysqlconnector://user:we all live in a yellow submarine@127.0.0.1:3306/alignment_research_dataset")
Makes sense, done.

2024-04-24 08:08 UTC, mruwnik approved these changes
nice

2024-04-24 08:08 UTC, merged